DB_LOCAL=true
DB_LOCAL_PASSWORD=0110
DATABASE_URL=postgres://postgres:0110@localhost/integrador
GOOGLE_OAUTH_CLIENT_ID=853000099698-mja71sb0chsva2m9eu3prpktl31psg5q.apps.googleusercontent.com
GOOGLE_OAUTH_CLIENT_SECRET=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
GOOGLE_OAUTH_REDIRECT_URL=https://g6v9psc0-5173.brs.devtunnels.ms/auth/google/callback
smtp_username=gerenciadordecontratosgdc@gmail.com
smtp_password='hynb cigg mwgl ehtc'