name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: Gerenciador de Contratos/src-back
      run: cargo build --bin gerenciador-de-contratos --verbose
    - name: Run tests
      run: cargo test --bin gerenciador-de-contratos --verbose
